# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plot_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pyqtgraph import PlotWidget
import pyqtgraph as pg
import numpy as np
import sys
import serial
import struct


class uiDialog(object):
    def __init__(self, ser):
        self.ser = ser
        self.timer = QtCore.QTimer()
        self.timer.timeout.connect(self.update)
        self.font = QtGui.QFont()
        self.font.setPixelSize(20)
        self.label_style = {'color': '#FFF', 'font-size': '20pt'}
        pg.setConfigOption('background', 'k')
        pg.setConfigOption('foreground', 'w')
 #       pg.setConfigOptions(antialias=True)


    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1656, 997)
        self.graphicsView = PlotWidget(Dialog)
        self.graphicsView.setGeometry(QtCore.QRect(10, 10, 1631, 931))
        self.graphicsView.setObjectName("graphicsView")
        self.splitter = QtWidgets.QSplitter(Dialog)
        self.splitter.setGeometry(QtCore.QRect(10, 950, 1631, 41))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.pushButton = QtWidgets.QPushButton(self.splitter)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.splitter)
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.pushButton.clicked.connect(self.draw)
        self.pushButton_2.clicked.connect(self.clear)

        self.graphicsView.getAxis('bottom').setPen('w', width=2)
        self.graphicsView.getAxis('left').setPen('w', width=2)
        self.graphicsView.getAxis("bottom").setStyle(tickFont=self.font)
        self.graphicsView.getAxis("left").setStyle(tickFont=self.font)
        self.graphicsView.getAxis("bottom").setStyle(tickTextOffset=20)
        self.graphicsView.getAxis("left").setStyle(tickTextOffset=20)
        self.graphicsView.setLabel('bottom', "Time (µs)", **self.label_style)
        self.graphicsView.setLabel('left', "LED Current (A)", **self.label_style)

        ax1 = self.graphicsView.getAxis('bottom')  # This is the trick
        ax1.setTickSpacing(100, 100)
        ax2 = self.graphicsView.getAxis('left')  # This is the trick
        ax2.setTickSpacing(0.1, 0.1)

        self.graphicsView.setXRange(0, 1440, padding=0)
        self.graphicsView.setYRange(0, 0.1, padding=0)


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Draw"))
        self.pushButton_2.setText(_translate("Dialog", "Clear"))

    def draw(self):
        self.timer.start(50)

    def update(self):
        self.ser.write(b'\x01')
        s = self.ser.read(1600 * 2)
        y = list(struct.iter_unpack("1600H", s))
        y = list(y[0])
        y = [(3.3 * num) / (2 * 65535) for num in y]
        x = list(range(1600))
        x = [num * 0.9 for num in x]
        self.graphicsView.plot(x, y, pen=pg.mkPen('w', width=1), clear=True)

    def clear(self):
        self.timer.stop()
        self.graphicsView.clear()


if __name__ == "__main__":
    ser = serial.Serial('COM7')
    ser.close()
    ser.open()
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = uiDialog(ser)
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
